/**:
  ros__parameters:

    #Mass and inertia
    mass: 2.0 #kg
    ixx: 1.0
    ixy: 0.0
    ixz: 0.0
    iyy: 1.0
    iyz: 0.0
    iyy: 1.0

    #Geometry
    L_m: 0.1 #m : Distance between the CG and one of the main motors
    L_d: 0.1 #m : Distance between the CG and one of the depth motors

    #Main motors parameters
    alpha: 0.785 #Angle d'inclinaison des moteurs
    Kd_m: 0.001
    rot_max_m: 200.0 #rad/s

    #Depth motors parameters
    Kd_d: 0.001
    rot_max_d: 200.0 #rad/s

    #PWM
    PWM_0: 1500.0
    PWM_max: 1900.0
    PWM_min: 1100.0

    PWM_M_sat_min : 1400.0
    PWM_M_sat_max : 1600.0
    PWM_MP_sat_min : 1300.0
    PWM_MP_sat_max : 1700.0

    #Drag

    #PID parameters
    
    # Position controller parameters
    x_PID: {P: 0.0, I: 0.0, D: 0.0, I_max: 2.0 }
    y_PID: {P: 0.0, I: 0.0, D: 0.0, I_max: 2.0 }
    z_PID: {P: 10.0, I: 0.0, D: 0.0, I_max: 2.0 }
    
    # Velocity controller parameters
    vx_PID: {P: 50.0, I: 0.0, D: 0.0, I_max: 2.0 }
    vy_PID: {P: 50.0, I: 0.0, D: 0.0, I_max: 2.0 }
    vz_PID: {P: 20.0, I: 0.0, D: 0.0, I_max: 10.0 }

    # Attitude controller parameters
    roll_PID: {P: 1.0, I: 0.0, D: 0.0, I_max: 2.0 }
    pitch_PID: {P: 1.0, I: 0.0, D: 0.0, I_max: 2.0 }
    yaw_PID: {P: 50.0, I: 0.0, D: 0.0, I_max: 2.0 }
    
    # Rate controller parameters
    p_PID: {P: 0.001, I: 0.0, D: 0.0, I_max: 2.0 }
    q_PID: {P: 0.001, I: 0.0, D: 0.0, I_max: 2.0 }
    r_PID: {P: 10.0, I: 0.0, D: 0.0, I_max: 2.0 }

    #Saturation
    vx_max: 1.0 #m/s
    vy_max: 1.0
    vz_max: 1.0

    p_max: 1.0 #m/s^-2
    q_max: 1.0
    r_max: 1.0

    Fx_max: 200.0 #N
    Fy_max: 200.0
    Fz_max: 200.0

    Mx_max: 500.0 #N*m
    My_max: 500.0
    Mz_max: 500.0